// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginResult struct {
	Result bool   `json:"result"`
	Token  string `json:"token"`
}

type Role struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Role     *Role  `json:"role"`
}

type UserFilter struct {
	And       []*UserFilter `json:"AND"`
	Or        []*UserFilter `json:"OR"`
	RoleIn    []int         `json:"roleIn"`
	NameLike  *string       `json:"nameLike"`
	PhoneLike *string       `json:"phoneLike"`
}

type Users struct {
	TotalCount int     `json:"totalCount"`
	Users      []*User `json:"users"`
}
